### ISSUE TITLE
verification status

### ISSUE THREAD

**Issue by mahmoudtavallaei** [masouduut94/Digikala_comments_verification#1]
با سلام مقادیر verification status را چجوری میشه بدست اورد؟

**Comment by masouduut94** [comment]
سلام

داخل دیتاست هستش 

یه نگاه به این لینک بندازین 
فایل train.csv هستش

https://raw.githubusercontent.com/masouduut94/Digikala_comments_verification/master/data/original/train.csv

**Comment by mahmoudtavallaei** [comment]
ممنون بله دیدم ولی منظورم از لحاظ کد نویسی از چه الگوریتمی استفاده شده برای بدست اوردن این مقادیر؟

**Comment by masouduut94** [comment]
منظورتون الگوریتم های یادگیری ماشینی که استفاده کردم برای تشخیص این 
verification status
چی هستش؟
@mahmoudtavallaei 

اگر منظورتون اینه که خوب الگوریتم های متفاوتی رو نوشتممثل 

LSTM, Bidirectional Lstm, Stacked LSTM, Convolution - Parallel Convolution and LSTM 
و ...

می تونین تو فایل های متفاوت نتایجشون رو ببینین
